# Small group session {.center}

A chance to design with your peers.

## There is no industry standard for deliverying environments

- We want to hear your proposals!

## Goal

::: {.columns}

::: {.column width="50%"}
[**Deliverable 1:**]{style="color: #1f4e79;"}

- Who are the key stakeholders to a regulated R environment?
- Are you aiming to solve specific pain points?
:::

::: {.column width="50%"}
[**Deliverable 2:**]{style="color: #1f4e79;"}

- Whiteboard a proposed architecture to test and provision 'post risk review' packages
- Highlight key experiences. E.g. updating packages, new packages, internal vs CRAN, etc, adding or updating unix level dependencies, etc
:::

:::

## Part 1: In the next hour

We will divide into 4 groups;

- Whiteboard a high level architecture
- You decide whether you map out the entire architecture, or tackle specific ke problems!
- Be prepared after the coffee break to present for 10 minutes!

## Part 2: Presentations

- Each group has 10 minutes to present with 5 minutes for questions
- Focus on what you think is most useful to share
    - That could be going deep into an end to end architecture OR you could share a high level architecture, and focus in on key pain points you've discussed and plans to mitigate them
- Please make sure to flag any impact or deeper dives you felt were needed, with stakeholders spanning from IT Quality to end-users.

---
